# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Minsu Kim
description: Minsu's persoanl website
baseurl: ""
url: "https://mskimalltoohuman.github.io"
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About
      slug: /
    - name: Research
    - name: CV
      external_url: "https://fsu-my.sharepoint.com/:b:/r/personal/mk24bb_fsu_edu/Documents/mskimalltoohuman/CV%20Minsu%20KIm/CV_Minsu_Kim.pdf?csf=1&web=1&e=zk6Zkm"

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: mk24bb@fsu.edu
#    - type: wechat
#      value: YourWeChatUsername
#      link: "#"
  follow:
    - type: philpeople
      name: Philpeople
      link: https://philpeople.org/profiles/minsu-kim-1
#    - type: twitter
#      name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
