# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Minsu
description: Minsu's persoanl website
baseurl: ""
url: "https://mskimalltoohuman.github.io"
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About Me
      slug: /
    - name: Research
    - name: CV

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: mk24bb[at-symbol]fsu[dot]edu
    - type: philpeople
      name: Philpeople
      value: https://philpeople.org/profiles/minsu-kim-1
#    - type: wechat
#      value: YourWeChatUsername
#      link: "#"
#  follow:
#    - type: twitter
#      name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
